project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "posts/*.qmd"
    - "!posts/lss_problem.qmd"

lang: zh-TW

website:
  title: "吟耘札記"
  description: "YinYun 的生活隨筆、人生雜想與學習札記。"
  site-url: "https://yin-yun-li.github.io/myBlog/"
  search: true
  open-graph: true
  back-to-top-navigation: true
  navbar:
    background: none
    pinned: true
    logo-href: "/about.html"
    right:
      - href: index.qmd
        text: 文章
        icon: book
      - href: https://yin-yun-li.github.io/
        text: 學術頁
        icon: mortarboard
      - icon: rss-fill
        text: 訂閱
        href: index.xml
  page-footer:
    left: "© 2026 YinYun Li"
    center: "常著文章自娛，頗示己志。"
    right:
      - icon: rss-fill
        href: index.xml
        aria-label: RSS
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    color-scheme: auto
    include-in-header: header.html
    css: styles.css
    lightbox:
      match: auto
      effect: zoom
      desc-position: bottom
    toc: true
    html-math-method: mathjax
    theme-color: "#457688"

execute:
  freeze: auto
