---
title: "21世紀後的聯準會"
author: "YinYun Li"
date: "2026-01-29"
categories: ["貨幣政策", "經濟學"]
---

::: {.callout-note appearance="simple" icon=false}
本文對應[柏南克談聯準會](https://www.books.com.tw/products/0010942230?srsltid=AfmBOoq_PafAnTFt5lVkKygk0uEBPW6ULgit8RD2U883zRdk8wc3EINV)一書Ch8,9,10,13。
:::



# 葉倫至鮑爾

如同葛林斯潘一樣，2014年接任柏南克之後的葉倫，需延續前任的政策方向，以及鞏固聯準會已有的成果——包含利用各種方法降低失業率，並提振過低的通膨。即便任內持續推動QE退場的進度，直至2016年中，葉倫僅主導一次升息，部分意外的局勢發展^[人民幣貶值、小衰退與英國脫歐。]使得FED對升息的行動更為謹慎。

葉倫時代面對的一個較為廣泛的問題：菲利浦曲線是否還存在？傳統菲利浦曲線解釋1960年通膨上升原因，卻在1970年的停滯性通膨踢到鐵板。於是經濟學家對菲利浦曲線做了兩個修正：引入供給面衝擊與通膨預期^[如果勞工預期通膨會持續上升，要求更高薪資維持購買力，企業於是透過提高售價獲利，形成自我實現預言。]。1980年初，伏克爾的升息抗通膨符合傳統菲利浦曲線的預測，但在1990年代後，通膨對失業率的關係變得相對扁平：比如金融危機後，失業率大幅升至10%，通膨卻只是溫和下降；葉倫時代原本準備透過升息來避免即將過熱的景氣，卻發現通膨率依舊低於目標水準。

另一個特徵是，若沒有重大供給衝擊，通膨經常是長時間維持穩定，這某一部分歸功於伏克爾之後，FED成功錨定大眾的通膨預期。這樣的好處是，貨幣政策者有更大的空間利用寬鬆政策因應景氣衰退，但這同時也代表通膨不再是預測經濟過熱的可靠指標，一旦通膨過高，把通膨降至目標水準的成本也會比以往更高，這對央行長期樹立的信譽有不利的影響。

不過葉倫在任僅4年的時間，川普於2018年提名非經濟學背景的鮑爾接任聯準會主席。即便在政黨背景上與總統相近，但他致力於維持聯準會決策的獨立性。在鮑爾剛上任的前幾個月，川普未曾批評其主導的貨幣政策，但在五個月後，後者就開始對聯準會的升息不太滿意^[據傳有研擬過換掉鮑爾的可行性，但法律上基本上並不得任意解任，以保護聯準會的不受政治侵擾的獨立性。]。

不過，鮑爾在2019年轉向，提到目前為止的升息政策，對成長放緩、貿易局勢惡化的經濟體來說，有點太多了，並在該年的AEA年會說明政策轉向是因應市場訊號與不斷變化的前景，根據資料做出靈活地反應，並非屈服於總統的壓力與要求。

這裡稍微補充，2018年8月傑克森霍爾會議，鮑爾說明自己的貨幣政策方法，多少帶有一點不可知論的做法，也就是減少模型導向的預測與分析，偏向透過經濟資料、商界與坊間人脈的在地資訊進行風險管理，以應對經濟前景的不確定性，因此作法上近似於葛林斯潘。

在2019年貿易戰、削弱的財政刺激與疲軟的經濟體，使殖利率曲線呈現倒掛的現象，而鮑爾此次降息作為一種期中調整，避免美國受貿易不確定、全球經濟減緩等影響，最後似乎也達成軟著陸的目標，至少收益曲線反轉消失。

在新冠疫情前，鮑爾推行聯準會傾聽(Fed Listens)，讓央行的檢討的內容將會擴及外界，除了讓大眾理解央行政策架構的調整與實行邏輯，也能讓政策制定者理解市場參與者對聯準會與其政策看法。這個檢討過程並然涉及對於操作架構(如何實行貨幣政策)的思考。

傳統貨幣政策，是透過公開市場操作控制聯邦基金利率，這屬於短缺準備金體系(scarce reserves)；但在金融危機後，聯準會早已處於充足準備金體系(ample reserves)。在準備金氾濫的情況下，出售證券收回準備金的升息方法不太可行，僅能利用超額準備金付息與附賣回交易來升息。而在2019年1月，FOMC決定採用後者，這也代表聯準會資產負債表規模永遠比過往大，並存在未來可能重新啟用QE的選項。

# 新冠疫情

疫情重溫了金融危機期間的痛苦記憶，如同金融危機期間金融市場的反應，短期債券賣光後開始拋售長期債券，以至於利率飆升、流動性枯竭。聯準會也如過往一樣充當最終貸放人，為附買回市場與交易商提供貸款、直接購買美國公債與MBS、與外國央行的換匯協定。

與此同時，鮑爾也推行了新的貨幣政策架構——彈性平均通膨目標制 (FAIT)，操作邏輯是讓平均通膨率維持在目標附近，而非傳統方法的既往不咎，也就是忽略過去未達標或超標的部分。因此，給定近幾年通膨未達標準，FOMC會讓通膨率在一段時間內稍高於2%，允許利率維持於較低水準更久的時間。FAIT給予聯準會決策與判斷的彈性，因為沒有具體定義通膨率的平均期限、究竟高於2%多少，而彈性的代價即是增加對市場溝通的成本，以及潛在的誤解風險。

不過，如果市場相信並理解這項機制，將能有效維持人民的通膨預期，在短期利率處於下限時發揮功效，央行也能更積極確保充分就業。也就是說，FOMC結束了過往先發制人的打擊通膨策略，不再以「今天的低失業率必然導致未來的高通膨」作為執行政策的假設，而平坦的菲利浦曲線與穩定通膨預期都降低了潛在的高通膨風險。

# 新工具
Bernanke(2020)估計結果顯示，因為傳統貨幣政策受限於利率下界，若名目自然利率為2至3%，量化寬鬆與前瞻性指引可帶來將近3%額外的降息空間；然而一旦遇到比正常情況更嚴重的衰退，或是原先的自然利率低於上述的區間，此時聯準會就需要額外的財政刺激或思考新的貨幣政策工具。主要有：購買更廣泛的金融資產^[QE主要是購買政府公債或政府擔保債務，一些外國央行則會購買公司債、商業本票、銀行發行的抵押貸款擔保證券等]、貸款融資計畫、負利率與殖利率曲線控制。

## 貸款融資計畫(funding-for-lending schemes)
某些外國銀行會補貼銀行貸款，主要為專門貸款給家庭或小企業的銀行提供資金，因為後者非常依賴銀行信貸，無法透過股市或債市融資。比如2008年10月歐洲央行設立的長期再融資操作(long-term refinancing operations, LTRO)、2014年6月長期再融資操作計畫(targeted LTRO program, TLTRO)，整體朝向低利率(甚至來到負的)、延長償還年限、放寬抵押品規定，但重點是要確保錢流入家庭與非金融事業。這些計畫降低了銀行融資的成本、增加對私部門放款。聯準會在2008年金融危機後並未推行此計畫，市場告訴他們，新貸款成長有限並非融資成本高，而是缺乏信用良好的借款人；然而到了新冠疫情期間，在國會與財政部的支持下FED推行類似的機制，比如中型企業貸款方案，這項計畫與國外的貸款融資計劃不同處在於，聯準僅購買95%的銀行貸款，承受大部分的倒帳風險^[前者則是將發放給家庭與企業的貸款，放在銀行本身的資產負債表]，目的在於降低銀行的道德風險。不過這項計畫因為嚴格的審查條件，實務上很少被銀行使用。

此外，聯準會在疫情間的貸款方案被視為緊急金融穩定機制，而非貨幣政策的一環，或許這種特殊方案在未來很可能會用於補充現有的貨幣政策工具，資金源自於貼現窗口，既無需13(3)授權，也無須財政部的資金挹注。這種作法只需要講明聯準會的貸款利率與類別，其中若貸款利率低於支付給銀行的準備金利率，將減少聯準會上繳國庫的利潤。

## 負利率
此政策的邏輯在於，準備金是銀行的資產項、央行的負債項，央行對銀行存在其準備金的帳戶收取手續費，突破了零利率下界，為貨幣政策爭取一些空間。最主要反對負利率的理由為，銀行無法對個人存戶設定過低的利率，負利率政策導致利差縮小，對銀行放貸產生不利影響。然而，書中提到了幾個實證研究，說明此政策似乎沒有嚴重損害銀行利潤，反而可以提高盈利能力[^ref]。因為低利率增加銀行投資組合資產價值、降低從存款之外融資的成本，而央行採用分層存款利率，只對準備金超過一定水準者收取費用，減緩負利率對銀行獲利的衝擊。實務上，歐洲央行很喜歡採用這個政策，但在FED並不討喜，因為貨幣市場共同基金在美國相對盛行，一旦資產變成負報酬[^negative_rate]，將會導致大量贖回潮。

## 殖利率曲線控制
相對於先決定購買數量再決定利率的QE政策，殖利率曲線為先鎖定債券殖利率目標，再讓市場決定達成該目標需購買的債券數量。好處是可以鎖定長期利率，比起短期利率，前者更能直接影響投資支出決策；此外，若市場參與者相信央行，不必實際購買債券就有機會錨定殖利率水準，算是一種用資產負債表作為政策背書的前瞻性指引。另一方面，收益曲線控制的缺點在於，假設央行宣布固定10年期公債殖利率，一旦經濟前景或溝通改變，市場參與者不相信未來這麼久的時間，央行都會維持同樣的利率，甚至可能放棄已宣布的目標，將影響原先央行樹立的公信力；又或者為了維持目標而大量買進未到期公債，將使退場變得更困難(承受潛在的、龐大的資本損失)。

回顧歷史經驗，為何1951年前FED^[當時有類似的作法。]或今日日本央行，可在不買債券的情況釘住長期殖利率，而今天的聯準會反而不行？因為現在美債市場有高度流動性，聯準會反而難以控制長期殖利率。即便如此，柏南克提議仍可考慮控制短中期的殖利率，因為FOMC可以合理承諾2、3年內維持固定利率水準；然而，假設在市場已經相信聯準會會將利率維持於低檔一段時間，這種方法就沒有更大的刺激效果，只能作為備案。

# 新架構

::: {.callout-note title="聯準會貨幣政策演進"}
我們先簡單回顧一下過往聯準會曾採用的貨幣理論與架構，並對近幾年FOMC檢討會提及的新政策架構進行討論：

- **金本位**
- **葛林斯潘風險管理法**
- **2012通膨目標機制**
- **2020平均通膨目標機制(FAIT)** 
:::

## 通膨目標機制的變體
2012年1月，FOMC採用的架構為「標準」通膨目標機制，事先宣布具體的通膨數字或區間並實踐。央行在實務上通常採行彈性的辦法，比如美國在追求物價穩定外也重視就業最大化。通膨目標機制是透明與可究責的展現，因為採用此機制的央行通常會針對經濟預測與政策分析，公開提供資訊。在現實情境中有很多因素導致通膨率偏離目標，央行對此如何因應，其實也能幫我們劃分通膨機制的不同變體。如果是標準通膨機制，通膨若超標或未達標，政策制定者的任務為讓它回歸目標，既往不咎。

另一種形式的通膨目標機制稱為物價水準目標制(price-level-targeting)。假設一籃子商品初始價格為100美元，央行宣布菜籃價格以每年2%成長，所以整個物價水準的軌跡為：第一年100美元、第二年102美元、第三年104美元，以此類推。然而，一籃子商品價格在第二年只有漲到101美元，也就是實際通膨率小於央行的設定，央行必須在第三年讓價格提高至104美元，才能回到原先的價格水準路徑^[標準通膨機制則是讓物價漲至103美元，維持原先2%的通膨率。]。

物價水準目標制的優點在於，減少長期生活成本的不確定性，讓家庭與企業規畫更容易；若景氣衰退是由需求面變動所引起，央行會設法將通膨率提高至2%以上夠長的時間，讓物價水準回歸原先的路徑，這種更寬鬆的政策力道，更能讓市場相信長期低利率的政策，並幫助經濟體盡快恢復就業。然而，此機制的缺點在於難以向大眾解釋，進而影響可信度與有效性；此外，若通膨為供給面的衝擊所產生，為了完全抵消物價上漲，就必須把通膨壓在平均水準之下，這等於是在景氣不好時有採用緊縮政策。

為了解決這個問題，暫時物價水準目標制(temporary price-level-targeting, TPLT)強調只有在短期利率處於下限時，努力維持利率以彌補之前未達標的通膨；一旦平均通膨率回到2%，FED就能將資金利率從下限往上拉。這個政策的意義在於，通膨超標不須隨後調成低於目標，以避免供給面衝擊帶來的問題。

2020年，聯準會實施FAIT架構，試圖融合三種變體的元素：保留標準2%的通膨目標，當聯邦基金處於下限時，採用TPLT讓平均通膨達到2%才緊縮政策，其中這個原則是不對稱的政策結構：只允許以超標來彌補未達標的通膨，卻不允許以低於目標來補償通膨超標。此政策架構在疫情期間就像一個隨堂考驗：只要能錨定通膨預期，只需要等待供給面衝擊消退，貨幣政策者不需要做任何的事情。總結來說，FAIT反映了FOMC當前的隱憂：通膨過低才是現在的問題，在標準通膨目標下，長期低於通膨目標將降低通膨預期，進一步降低自然利率，壓縮貨幣政策的空間。



## 名目GDP目標制(Nominal GDP Targeting)
根據定義，名目GDP成長率等於實質GDP成長率加通膨率，央行若以名目GDP成長率設定目標，可以傳遞向市場傳遞明確的訊息，既關心實質成長，也關心通膨，這與雙重目標不謀而合。另外，名目GDP目標制可能對央行因應自然利率下降更有幫助。假設實質成長率與實質自然利率都減少1%，後者會讓名目利率下降1%，限制央行寬鬆政策的能力；但固定名目GDP成長率的目標，則必須讓通膨提高1%，使得最後名目自然利率不會下降，因此保留了降息的空間。

FOMC曾在過往討論這個方法卻被否決，相對於標準通膨目標讓FOMC彈性平衡雙重目標，名目GDP目標制對兩者都賦予相同的權重，更何況達到名目GDP成長率(5%)，可能是犧牲了成長率(0%)，換取了極高的通膨(5%)所達成，這樣反而違背了雙重目標。

## 提高通膨目標
還有一種做法是保留標準通膨目標制，但提高目標，比如從2%提高至4%。投資者會要求更高的名目利率獲得額外的通膨補償，這樣聯準會將獲得額外的降息空間。不過這個方法的缺點顯而易見：持久的高通膨為市場增添了雜訊，不利於經濟決策，更重要的是損害央行長期建立的信譽。數十年來通膨預期已穩定在最初設定的2%左右，若市場認為通膨目標將隨時間或經濟狀況改變，屆時必定難以重新錨定預期。而近年來的低通膨也使這項政策的實行面臨困難，如果更高的目標不可信，就無法達成自然利率上升的目標。雖然FOMC並未考慮這項措施，仍然FAIT架構中看到類似的影子。

## 財政政策
財政政策的好處在於，自然利率很低時，財政政策的效果不會打折，而低利率也降低政府發行公債的融資成本。在低利率時代，公債排擠儲蓄的問題相對不嚴重。另外，相對於貨幣政策，財政政策更容易鎖定經濟中需要幫助的產業與個體，前者只能藉由改善總體經濟來影響特定對象。然而，財政政策需要國會立法審議，短期內缺乏彈性，不像政治獨立的央行可根據經濟狀況迅速調整貨幣政策。

前面提到貸款融資計劃或量化寬鬆購買更多元的證券，都是聯準會額外獲得的財政權，原則上聯準會可得到的財政權是有限的，也不應該額外要求，除非國會理解也接收到提高聯準會財政自由裁量的影響，其中之一就是上繳國庫的利潤；另外，任何新權力不應附帶任何條件，以免影響貨幣政策的獨立性；最後，新工具只希望改善信貸市場的普遍運作與總體經濟，而非分配信用給特定對象。

此外，將財政政策作為穩定經濟的主軸，而貨幣政策為被動的角色並不明智。有些現代貨幣理論(Modern Monetary Theory, MMT)的支持者試圖削弱央行獨立性，並將財政主導制度化。他們認為應該把利率固定在低檔，讓貨幣融資與舉債融資沒有差別。這等於要求聯準會放棄打擊衰退與通膨的職責，更不利於經濟穩定。貨幣政策制定者尋找了許多提高貨幣政策效力的工具，但這些工具的不確定性在於取得政治共識。因此，除非能提高反景氣循環財政政策的靈活度^[有種方式稱為自動穩定機制(automatic stabilizer)：提前立法，在符合一定的經濟條件下，政府支出或稅收有對應的變化，但這在實務上很難達成。]，否則貨幣政策仍然是穩定經濟的主要工具。











[^ref]: 參見：[Lopez, Rose, and Spiegel(2020)](https://www.nber.org/papers/w25004), [Altavilla, Burlon, Giannetti, and Holton(2021)](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3460947)。

[^negative_rate]: 俗稱跌破1美元(break the buck)。