---
title: "跨不去的坎"
author: "YinYun Li"
date: "2026-01-19"
categories: ["高中", "人生"]
---

前兩天大學學測。距離上次大考已過了五年，有時候都會回去想，當時的我是不是在考試這條賽道上輸得很徹底？在大學階段似乎扳回一城，這樣算是成功嗎？不如把當初為了要投稿班刊而寫的文章貼出來^[後來班刊因為一些原因沒有編成，所以這篇一直留在我的電腦裡。]，看一下當時的文筆多矯情(誤)。

# 日暮思懷

書寫於2022/11/1。

> Life is full of trials and tribulations. All of us have mixed feelings about this three-year journey. On the one hand, success brought us to the point of ecstasy. On the other hand, failure threw us into the depth of disappointment. These bittersweet experiences not only provide us with some food for reflection, but they also strenghten our mindset. If we can keep thinking positive in the future, and try to practice self-kindness when we feel tired, we will rise above hurdles, overcome the ordeals, and fulfill our dreams .


信步於落日餘暉灑落的校園，一面靜靜感受周遭的喧擾，一面任腦中思緒如水般不斷流淌著，悲喜交錯之間，隱約勾勒出三年來點滴的回憶。

三年前，懷著一顆初生之犢不畏虎的勇氣，踏入這所夢寐以求的校園，雖說臉龐顯得青澀與懵懂，但內心早已稍稍縱容自己，在課業之餘，也接觸了許多的社團活動。在這大大小小的活動中，經歷時如酒般濃烈；回首來看卻如佳茗般，甘甜中卻帶點一種說不出的苦澀。一方面，這些活動著實豐富了三年高中的生活，填補生命中原本可能留存的空虛與遺憾；另一方面，卻是幾度心神憔悴，萌生了逃避與退意。

走在語資這條路上，可說是蜿蜒曲折。起初，是因為國中課業上的傾向與腦中閃過的那股衝動，讓我選擇踏入以語文領域專長的班級，想藉由豐富的資源，期許自己能成為一位語文領域的佼佼者。然而，因為外務的疲勞轟炸下，逐漸迷失了自己的方向，涉獵地過於廣泛，卻忽略了專注於當下。

在一升二的轉折點，我猶豫了十幾天，想著在這個班的價值，與未來兩年的去留，不斷地衡量在文理兩方面的成績，不知道是否應該追尋外人看好的理組之路，於是漸漸遺忘了那曾經為什麼想來到這個班的原因了。

經過多次討論與深思熟慮後，我決定留在這個班級。然而，外務再度使我迷失自己，幾度想遇見當初的自己，卻仍無法擺脫多重的壓力與羈絆，只能勉強度過了高二。即便如此，在痛苦的過程中，仍享有美好的時光，跟伙伴一起完成一篇巨量的深度報導，磨難的過程也有了美好的收穫，至少獲得了聽眾的掌聲與朋友的讚譽，這也令我心滿意足了。

來到高三時，確實應當全心往自己的目標邁進，然而腦袋在此時卻又在莫名其妙的打轉。明明已經走在文組這條路上，卻在幾度夜闌人靜的深夜，躺在床上的我，將雙眸投射在無底的黑暗深淵，想著自己的出路，並質疑著自己的抉擇是否正確；也有幾次不太想上課，面對著教學的內容與老師們，我想要遺棄這一切。

但，這不過是拋棄了自己。

學測前幾度的鬱悶與不順心，換得了考場上的失利。這樣的結局令我無地自容，同時也徹底地提醒了我：相信自己，就是走在該走的道路上。也因為一次的考試，我學會了忠於自己原本的選擇，並真正體認到，身邊的同學，將是我前進的目標，即使以往不曾察覺，但至少我省悟了。


於是，在高中生活的最後的189天裡，我的心境回到最平靜的狀態，看似枯燥乏味的講義、書籍與考卷，我卻甘之如飴，能心無旁騖的接下這下挑戰，並逐步走到最後。

謀事在人，成事在天。不斷的拚命，想要成就自己，卻還是差了那麼一點。月色灑在窗前的書桌與成堆的書卷，熱淚從臉龐滾落、濺滿了衣裳。我明白，現實，不如美好想像。但我不明白，這樣算是成功了嗎？還是應該否定自我的努力，承認自己依舊突破不了那道高牆呢？這個問題懸而未決，將伴著我，走向往後的人生旅程。

這三年，算得上精彩嗎？我是否過分執著於某些事情，忽視身旁的朋友，忘卻自己的初衷?在球場上，我能馳騁與放縱；在教室裡，我卻膽怯與拘謹。與人相處的每個當下，有欣喜、悲痛、愛慕、憎恨等錯綜複雜的情緒，逐漸交織出真實的自己，但哪一個又能代表我呢？除了自己，又有誰，能夠找到我呢？人常常走了太遠，卻找不回自己，因此我們需要有些許憑藉，沉澱自己紛亂的內心，找出那個塵封已久的答案。

如果生命是無心的故事，所以流逝；那麼故事便是多情的生命，所以長存。文字能夠串起過往的故事，記錄生命中的酸甜；高中三年的點滴，將鐫刻於生命中重要的扉頁，不曾抹滅。

直至雙腳踢到了遠方滾來的籃球，這才發覺，雖身在球場，心裡早已重溫了高中三年：一路上的跌跌撞撞，從懵懂無知到成熟老練，由天真無邪到憂愁滿懷。

晚霞仍在天一涯，卻已閃著數點星光。回首望向這片校園，腦海浮現許多帶不走的回憶，我強忍著淚水，揮手告別，悄然無聲地離去。

# 靜夜思懷

書寫於2026/1/18。

時隔四年重新看了前段的文字，想要補充一些細節。從小，我的家人並沒有限制我學習的方向，不像某些家庭強迫小孩要考醫學系、電機系。我覺得在國中時期，自己好像比較擅長文科，可能是讀起來比較容易上手，總能取得比較高的分數，也可以更直白地說，我非常會背誦，所以自然能掌握這些內容。另一方面，我小時候非常喜歡中國史，對於文史的熱忱延伸至對應的課內知識，在研讀的過程就感到特別開心。

這樣的熱情或許可以延續至高一上，日子久了，很難不被理組掛帥的校園氛圍影響。雖然都待在語資的環境，我還是會有意無意地被灌輸「重數理、輕人文」的觀念，地點就在尊賢街上的水利大樓^[這是一中出校門後，走幾步路就能到達的補習大樓。]。

國小的時候有被送去安親班，國中後就決定自己讀書不需依靠補習，輔以國三的加強班，讓我順利考上第一志願。不過在被高一上的數學考試所摧殘後，我就不太相信學校老師的教法，開始去補習。我當時遇到的補習班數學老師，評價上毀譽參半，從榜單來看確實成果豐碩，他的教學方法與風格頗有一套，感覺當時就是被他的魔力吸引，甚至著迷，開始有些自以為是的學習數學，而漸漸忽略學校老師的教學。然而，他的一些偏激的發言卻讓人不予苟同，甚至被他中傷。我的同學或許只是氣憤之下就離開了這間補習班，但我因為相信他的教學而選擇留下，只是就要一直承受他對文組的歧視性發言，這也對我的心情造成很多負面的影響：我逐漸淡忘了自己在語資的初衷是什麼，甚至到了高三時還覺得自己是不是走錯了路，當初應該轉組的。此外，我開始對學校老師的教學感到焦躁與不滿(不僅是數學科)，因為我沒辦法用一套自己的學習框架去理解老師的思維，那我心中就存在著一種對學校老師的不信任，陷入了一種認為只有靠自己才能解決的無底深淵。

事後來看，我承認那段時間，被補習班影響太多以致於心中怨念太深，沒有一顆堅定沉穩地心去考學測，那結果一定只能是慘敗[^gsat_res]。就連有補習班支援的數學，在考場的那個當下，我就預料到結果將會是全面崩盤，毫無懸念直接去指考。曾經以為靠著補習就能征服一切的不可一世，轉瞬間形成無止盡的懊悔與悲痛。花了很多時間檢討自己的不是，到底什麼原因走到了今天這步。或許真的就如我想像地一樣，過度依賴補習、心中存在著對自我選擇的雜念、對學校老師與知識的不敬，才造就今日的失敗。所以在考完的一兩個月，我花了一些時間跟自己的心對話，既然待在了語資，就該無悔地持續往前走，而非躊躇不前甚至懷疑過往的抉擇；面對各科，我都應該要放下身段好好學習，不是永遠照著自己的邏輯思考這些知識，而是更應該仰賴老師們的智慧，有關他們如何理解這些知識的技巧或思維，都是必須經過學習養成的。也因此，我的社會科在指考校正回歸；英文與數學看起來好像不錯，但我覺得那不是我應該有的表現，至於國文就更無言以對了。想當初自己也是國文科的佼佼者，為何進入高中後，跟國文科漸行漸遠，無論學測與指考，都考了差不多糟糕的分數。我都開始懷疑，是不是自己其實根本不是擅長語文的人[^english_cram]？

面對高中那個極度糾結的自己，我想安撫他，告訴他那個階段的煩惱根本不是煩惱，或者說不值得煩惱。假設遠光放長一點，知道自己在大學階段是在學什麼與做些什麼，我還會如此在意自己是不是文組的身分嗎？我還會很在意為什麼當初沒選考自然嗎？

我甚至認為當時的那些煩擾是瑣碎(trivial)且愚蠢的，縱使自己有選考自然的念頭，卻沒辦法轉化為堅持的勇氣與決心，並付諸實踐，反而是回頭過來責備自己把未來的道路縮死了，覺得對自己的學習不負責任，進而影響考試的心態。當然，沒有人知道未來會發生什麼事情，對18歲的人來說這一切都太過於遙遠，考高分變成那個階段唯一的目標，當分數夠高，理想校系任憑自己選擇。我當然沒有經歷過那段奢侈的過程，只是我花了很多時間彌補當時的執迷不悟，包裝成今日好像很優秀的樣子。

這段過去帶給我複雜的感受，因為它讓我痛苦過，卻也讓我格外珍惜走到今天是多麼不容易的事。從萬丈深淵從新爬至地平面，起步前行，彼時跨不去的坎根本不值一提，只要稍微轉向，繞過它並學習與它平和相處，日子一久，也就釋懷了。






[^gsat_res]: 我到現在還是不敢跟人提我的學測成績，有興趣可以來問我，你會把我輾在地上。
[^english_cram]: 說實在的，即便高中跟著補教名師學英文，到現在還是覺得自己的英文非常破，感覺虛擲了父母不少的金錢😞。

