---
title: "吉他社與科志"
author: "YinYun Li"
date: "2026-02-01"
categories: ["高中", "人生"]
---

# 吉他社
每年吉他社成發，總會回去一中看表演與吃飯。去年年底是吉他社46屆成發，我又回到記憶模糊的演奏廳，看舞台的學長或學弟妹們表演。老實說，我已經很多年沒有彈吉他了，甚至很難說服自己現在還喜歡自彈自唱，或者在舞台上表演本身。

我在[跨不去的坎](high_school_study.qmd)提到自己升上高中後外務頗多，第一件事就是開始玩社團。在高一的時候還搞不太清楚狀況的情況，想說可以從社團中開發一些讀書以外的技能，於是我參加了民謠吉他社，從零基礎開始學吉他^[小時候在外面學過一點吉他，不過沒多久就忘了，學的也不怎麼樣。]。我感覺是當時遇到了一群不錯的社團幹部學長，被他們的教學與實力所吸引，徹底點燃了學吉他的熱情，並努力參加吉他社相關的活動，並在過程中認識了一些好友，後來攜手成為社團幹部。

不過在高一是學弟的時候，我就有感受到自己的吉他能力僅停留於複製，而無法創新。同時，我需要花大量的時間練習一個比賽曲目，卻無法顧及大量的課程練習。說真的，我也不知道當時哪裡來的勇氣，想擔任幹部，甚至還想徵選教學。即便確保自己在對外場合的表演有低失誤、高品質的演出，平時在暑訓、寒訓或帶學弟時，我是非常心虛的——因為我明白自己其實不太懂音樂，尤其在樂理的部分，我腦袋轉得是特別的慢。在同屆的cover下，我也是裝腔作勢度過了一年的幹部生活，在成發上表現得自己好像很厲害的樣子，其實過完高二那年，總覺得自己的吉他並沒有特別的長進。

另一方面，過多的社務、教學與自學的壓力，加上語資班的小論文，讓我開始有點討厭這個地方。過程中花費太多的時間，卻沒有感受到把事情弄好與前進的感覺。在高二的尾段就有在思考，即便高二幹部生涯已然結束，是否就此退出吉他社，不要再跟這個地方有所瓜葛。基於人情壓力的留在這裡，以後看到大屆學長、同屆甚至是學弟妹，心中總會有點感到無地自容。

幾次跟大學室友吃飯聊到這個，他跟我的想法全然不同：我是因為高中的經歷，有時候總會後悔投入吉他社太多；他是因為高中沒什麼社團活動，反而羨慕我當時可以參加吉他社、學會自彈自唱。即便當時學得再好(或者只是表面上看起來很好)，隨著大學生活的展開，我也逐漸減少接觸吉他的時間，更別說以大屆的身分回一中表演(我的同屆到現在還是會在學弟妹的成發出歌)。可能逐漸體會到，音樂不是屬於我投入的地方，或者說投入的成本太大，我還有更想做的事情(做學問與研究)。沒辦法，感覺繞了一個圈，好像只有讀書是讓自己自在的事情，因為不需要看人臉色、同時是自己擅長的事情，有辦法毫不心虛的展示與分享。

雖然在吉他社後半段待的不自在，我還是很感謝同屆給我淡出的空間與時間，讓我可以心無旁鶩地忙碌自己的事情。只是在當時內心如千絲萬縷般被纏繞，愈理愈亂，我任性的選擇似乎也帶給身邊的人不少困惱，而高中後半段就在這難以割捨的人情網絡度過，我只能若無其事的抽離吉他社一年^[嚴格上來說高二的幹部在高三成為顧問，必須驗收高二幹部大大小小的事務，這對當時的我來說是個困惱。]。

過了這麼些年，大家可能也忘記了當初這段拉扯與個人內心的掙扎，我也好像能若無其事地定期聚會、見見雅惠老師^[一中吉他社的大家長，記得當初想退出時，老師苦口婆心勸我留下來。]。我已經忘記了這段過去到底對我來說多重要，這些共事的夥伴與經歷的風景，現在看來離記憶已經愈來愈遠——生活圈逐漸分離，每個人各自忙各的事情，而我也沒有勇氣再把吉他拾起，每次來到演奏廳與團部，都有種與吉他社抽離的感覺。或許，一中吉他社就是有著這樣難以理清的羈絆存在，因為同屆、因為學長與老師，會讓人想再回過頭來品茗一下這段過往的苦澀與甘甜，即便離記憶愈來愈遠、愈來愈遠，我還是願意回來看看熟悉的人、唱幾句社歌。就算拾起的碎片無法拼湊出一個完整的過去(或者說那段過去本身就不完整)，我還是很珍惜有遇到這些人，時隔多年還會連絡的好同屆。

# 科博館志工

這是我高中參加的第二個團體，名義上不是社團卻像是社團的性質般存在。記得是高一參加了科博館的一日遊後，就決定加入這個團體，不過在徵選的過程並非一帆風順，經過了三輪面試才成為了科志的一份子。主要的工作就是每個月(可能記錯了，反正就是固定某個時間)要去科博館值勤，工作在值勤當天由所謂的「大哥」或「大姊」選定，跟另一個夥伴要在館內的某處值勤。說真的已經太久沒有去科博館了，現在完全記不得有哪些值勤的點，依稀有印象的可能是數位服務台、製作恐龍卡的櫃檯等。

其實這份工作科博館自己也有透過校外的管道徵選，科志這個團體主要由四校聯合(一中、女中、文華、二中)，會辦兩場大型的活動——春遊與一日遊。回去看我典藏已久的ig貼文，只能說不忍直視^[不知道為何，現在看到以前寫的文字都覺得很肉麻😔。]，不過我還是勉為其難地放上來。

## 春遊
書寫於2019/6/7。

猶豫了好久好久，還是想寫一下。

發這篇文之前，常藉自己事務繁多的之由，不斷推託。但我想，如果不在這段時間寫些什麼，幾個月以來，那片刻的美好，也許會隨時光的流逝而逐漸抹去。

科志，是顛覆高中生活想像的大家庭。因為遇到了你們，在自己預期的康莊大道上，硬是轉向了一個完全沒有設想過的崎嶇山路，而自己竟也瘋狂似的踏上這條路途。從面試的幾次以來，不斷挑戰自己的極限，雖然結果並不能代表自己已經克服跟他人接觸的恐懼，但對自己的勇敢，卻也有些不可思議。

與大家主辦活動，是最深刻的收穫。看似選擇自己可能最擅長的一組，接觸之後又發現是另外一層的世界，否則怎麼會字為了要整齊，反而寫的歪七扭八？為了幾塊規則板，還需要勞心數個午夜？當個小組長，嘗試扮演領導者的身份，心裡卻經常害怕他人的指責，好幾次備感無力時，他人的批評似乎在耳邊響起。

跳舞跟演戲，對我而言，是一個奇妙的存在——想敬而遠之，卻又想深入嘗試。練習卡關大魔王，應該是非我莫屬了。早操，別人不到半小時就大致學好了，我花了一個小時，卻依然學不好;男舞，也不知道自己在跳什麼，每次驗完後給大家的感覺，就是自己究竟是在表演，還是小孩在隨便亂扭動？最後的成果，離他人還是有一段差距，但對一個舞障來說，似乎開展了僵硬的關節與封閉的肢體。

演戲，就是導演永遠會衝康演員，像自己莫名的就要演一個與自己性格不合的角色。不過，要克服心理方面的障礙，感覺又比跳舞容易多了。天文與中科，看似平行時空的兩條直線，開始有些不同的對話與巧妙的詮釋。永遠不會忘記段考前三天還在討論劇情，大家都為此作出這麼瘋狂的決定。在排演過程，有時經歷無限次的NG，或是一言不合就跟夥伴鬧彆扭，不過最後大家還是協力演出一齣戲。對我來說，這是第一次登上屬於自己的舞台，演出自認滿意的風格。

也許雨水澆熄對營火晚會的期待，卻澆不熄幾個月來，大家對一件事情的執著，以及對一個團體的熱忱;或許山區一隅能容納數十人的身影;卻承載不下兩天的玩樂的歡笑，瘋狂似的嘶吼，與最後離別的惆悵。

搭上遊覽車踏上歸途前，眼角的餘光流露出不捨與流連，試圖再看幾眼四周的風景，捕捉兩天以來的點點滴滴。春遊的結束，才是真正的開始，一切的心結會解開，彼此的不悅會釋懷，大家會更愛這個團體，更肯定當初那個奮不顧身的自己。

## 一日遊
書寫於2019/10/23。

9/7 31一日遊

一個不小心就把這段故事隱沒至腦海的角落了，就算再怎麼忙碌，這份回憶依舊抹煞不掉，對他的初衷與堅持。

這算是升上高中以來給我一份很重要的生日大禮之一吧！(我絕對不是因為拖稿而找藉口😂)從裡面，我認識了他們，同時也在追尋著自己。

事隔一年，回到當初時空交會的起點，彼此的相遇，似乎當時就埋下了伏筆，在茫茫人海中，有一群人，逐漸越走越近。

想起當初，也是一股腦兒的熱忱與衝動，想要加入一個團體，尋找曾經我擁有，卻不復存在的，歸屬與包容——也可能，其實那些根本不存在，都是虛幻而不實際的。

但在這條路上，我看到你們，一個個臉上清純而天真的微笑，總在一次次的轉彎處，停下來，佇足回眸，靜靜的等待著，後頭苦苦追趕的我，幾度沉悶的愁容，總因為你們的鼓勵，撫平那糾結的心理。

一開始真的很不自在，不知道這樣的連累與拖欠，對你們是多大的傷害？甚至悔恨彼此的相識，還在夜闌人靜時，仇視一個團體的感覺，認為像以前的自己一樣，走完一段屬於自己的路途，不是特別的悠閒而美好嗎？極端的仇恨感，反反覆覆地在心囚中打轉。

但經過一段時間後，每當走回斜陽映照下的三台，就想起志工歌熟悉的旋律；走過不停運轉的水運儀象台，就想到為了征服講區而付出的努力；綿密的青青草地在眼角餘光處，勾勒出大地伙伴的身影，對我的信任與鼓勵。

如今，看到了32，看到了無數個屬於自己的面孔——去年，也在台上，被恐懼與怯弱吞噬著，轉瞬間就這樣熬過了一年，看似快活，卻又感到極度不捨，不能體會，時光為何倏忽即逝。

總覺得時間是令人又愛又恨的，我喜歡它創造屬於自己的一段回憶，即使隔了數月、數年，總如品茗般，在某個午後，散發那清醇的芳香。另一方面，它卻又在事情發生的當下，無所不用其極地折磨他人，讓人有種痛不欲生之感。

但不論如何，不悅與痛苦都結束了。如果再給我一次選擇的機會，我是否會再度選擇這個團體，我想，渴望與感動應該會大於排斥的心理吧？既然我已經走過，那就不必再退後了，只希望未來的我們，還能擁有當初那份，塵封已久的典藏情誼。

# 後記

仔細想想，一日遊所描繪的感受，或多或少反映了高中參加兩個社團的自己，被排山倒海而來的事務淹沒後，開始不耐煩、討厭某個地方，卻又與身旁的人有難以割捨的感情在。遙想當時在苦痛結束不久，還會回到熟悉的地方討拍；然轉瞬之間，早已時隔五六年之久。吉他社因為成發的傳統仍會固定一聚，相較之下，一中科志的群組已塵封許久，每個人的生活交集愈來愈少，似乎也失去了聯絡的動機。

至於科志整屆是否結識了到現在還會往來的朋友，我的答案是否定的。或許是個性使然，在一切的熱鬧落幕後，我總選擇獨自一人走回適合自己的角落，待著、看著。有時候看著一些人仍保持著友好的關係，羨慕的背後多少帶有落寞的感受，卻也明白這種因緣是可遇不可求的。曲終人散可似淒涼，倒也落得自在大方。回憶固然美好，順著自己的心境去生活更為重要。這也是我在大學時，反而活得像是標準的高中學生，除了讀書外，就沒有去體驗各種好玩的大學生活。原因是我認為自己在高中階段已經玩夠了，而我也清楚自己接下來想要的是什麼，即便沒有他人眼中的精采大學生活，我也毫不在意。

也許自己適合當一匹在荒原裡奔馳的野狼吧！因緣際會，流連於春花秋月間，卻發現自己與眼前的景緻是如此格格不入，於是，我轉而回到舒適的雪白大地，踽踽獨行^[我寫這段話並不是指我的個性有多孤僻，只是我這個I人似乎只能常著文章自娛，以示己志。如果有志同道合者願意跟我來往，我還是滿開心的，畢竟在大學時真的是邊緣人中的邊緣人😔。]。