---
title: "語資"
author: "YinYun Li"
date: "2026-02-21"
categories: ["高中", "人生"]
---

寒假尾聲，想將高中回憶的最後一塊拼湊起來。[跨不去的坎](high_school_study.qmd)稍微描述了我高中時期，起伏不定的學習歷程，而此篇我想多講一些從語資班帶走的東西，即便有些破碎與不完整。在此之前，我先將個人的背景描述清楚。

我猜大部分的人，小時候都會因為接觸歷史古裝劇^[請注意，不是宮鬥劇。]而喜歡歷史，我也不例外，為此也主動去探索不少的歷史故事與書籍；我也喜歡看展，特別是文史類的展覽，了解古代生活與曾經發生過的故事，常帶給我很多的收穫。小時候談到夢想，總想著成為歷史學家或文史工作者。

與此同時，我也是一個很服從體制的好學生，長時間在課業打轉，不斷地想考好一次又一次的大考小考，獲得好成績、進入好學校。
國小時或許還有時間自由閱讀，國中之後，思想日漸成熟之餘，卻很少有看「課外書」的習慣。時至今日，我沒有真正拓展閱讀的深度與廣度，常感嘆自己書看得不多、看得不夠快。

或許這樣就沒辦法成為出色的文學家或史學家吧。畢竟這兩個領域都仰賴大量閱讀，而我好像缺乏這種訓練。或許，接下來只要好好鍛鍊即可吧？我只能說，長大要做的事可多了，再加上我發現自己即便有探索文史的興趣，卻沒有做文史的天分。

當然，剛考完國中會考的我並不會想這麼多，憑著感覺就報考了語資班，也沒什麼阻礙的就去讀了。我記得高一時的專題課，進行方式就是請大學教授到不同教室，每個人就依照自己選擇的類別跟不同的教授上課。我印象中自己選了比較多跟文學、歷史相關的專題，發現歷史學研究跟想像中的不一樣，不是只有找文獻讀文言文這麼簡單，當時接觸了一些歷史學研究的思維，我似懂非懂，聽久了就覺得挺無聊的。文學的部分，倒不是沒辦法吸收老師所說，只是感覺自己沒有甚麼人生歷練，寫不出好的作品。加上高中考大學時的國文表現，讓我覺得自己其實不是那麼擅長國文科，我只是很會背誦，與語言之間的連結愈趨模糊。

高二的時候，全班需要有「研究」產出，當時在老師的爭取下，產出的格式變得更加彈性，不拘泥於小論文，也包含紀錄片、深度報導等。我跟另外兩位同學做了一個非常大的題目，主題是從男女校的空間探討校園中的權力與性別。我們先從簡單的觀察出發，比如台中一中的校地遠大於台中女中、後者的地理位置更接近日治時期的行政中心——台中州廳，背後是否隱含日治時期的殖民者手握權力，對不同性別乃至於日台民族的差別對待。為此，我們走訪日治時期五州(臺北、新竹、臺中、臺南、高雄)的第一志願男女校，進行實地的踏查與便利抽樣，讓我們可以進行跨縣市校園的比較。這樣看起來很酷的題目，說真的也不是我們三個想出來的，是當時歷史老師心中的想法，我們把它做出來。所以嚴格說起來，我們並沒有經歷過形塑問題意識的過程，也沒有體驗過為了問一個好的研究問題而遭受折磨的過程。更多的是花了不少時間與精力走訪南北，統整觀察的照片與問卷，最後寫成100多頁的萬字報導。

最後，則是「語文資優班」這個頭銜本身。我常在思考，我真的是語文資優嗎？這個問句並非自謙，而是有所憑據。大考與檢定的成績告訴我，我並非語言資優，到現在英文聽力依舊是扶不起的阿斗，我還在想碩班生活即將到來，未來如何準備英檢、如何考高分申請國外學校？話說回來，這個班的訓練比較像是人社班，充其量只是多了第二外語的課程，我當時選修法文，不過我並沒有學得很好，或者說實話，我沒有認真學。

如果從人力資本的角度思考，高中三年在語資班的訓練，與大學階段的學習與研究是否有密切的關聯，我認為並沒有很多。我常在想，如果高中少玩一點，是不是就能多接觸人社領域的不同思想，讓我更清楚未來就讀科系的方向。還是說，只會花更多時間在課業知識，只為了考上社會價值期待的第一志願^[高中考大學的我有些眼高手低，心中想去台大管院，特別是財金系，後來分數根本達不到。]，我沒有真正問過自己想要什麼，接觸了文學與史學後，比起班上同學，發現自己或許不是那塊料。一直要等到大學修了經濟系的課，才逐漸了解經濟學是怎麼一回事，讓我想要從量化社會科學的視角接觸社會議題。

我想，或許是已經度過了臺灣體制下幾場重大的考試，讓我在大學階段能從容自在地探索自我。偶爾會感嘆自己蹉跎了小時候好多的時光，現在正慢慢地將那些遺憾拼湊起來，開始讀起書架上未曾翻閱的書籍、看起小時候沒有認真追過的電影與戲劇、將以前學得不夠透澈的知識[^3]補齊，以及跟現在的實驗室老師認真的做研究。即便無法快步跟上理想的樣子，只要每天都有成長一點，我想這樣就可以了。至於語資班在我的人生旅途中有甚麼重要的意義，我想這並不是特別重要，如果每件事情都一定要賦予一個舉足輕重的地位，那也活得太累了[^4]。


[^3]: 主要是英文與數學。
[^4]: 而且某種程度上有點浪費時間。逝者已矣，來者可追。